app = "planish"
primary_region = "fra"

[build]
  [build.args]
    GO_VERSION = "1.24.5"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "plan_db_volume_1"
  destination = "/app/data"
